#ifndef SOGE_PHYSICS_IMPL_PHYSICSCOMPILEPREPROC_HPP
#define SOGE_PHYSICS_IMPL_PHYSICSCOMPILEPREPROC_HPP

#include "SOGE/Utils/PreprocessorHelpers.hpp"


#define SOGE_REL_COMPILED_PHYSICS_IMPL_HEADER(Suffix) SOGE_REL_COMPILED_IMPL_HEADER(SOGE_PHYSICS_IMPL, Suffix)
#define SOGE_ABS_COMPILED_PHYSICS_IMPL_HEADER(IncludeDir, Suffix)                                                  \
    SOGE_ABS_COMPILED_IMPL_HEADER(SOGE_PHYSICS_IMPL, IncludeDir, Suffix)
#define SOGE_MAKE_PHYSICS_CLASS_FRIEND(ClassName) SOGE_MAKE_IMPL_CLASS_FRIEND(SOGE_PHYSICS_IMPL, ClassName);


#endif // !SOGE_PHYSICS_IMPL_PHYSICSCOMPILEPREPROC_HPP
