#ifndef SOGE_SCRIPTING_SCRIPTINGCOMPILEPREPROC_HPP
#define SOGE_SCRIPTING_SCRIPTINGCOMPILEPREPROC_HPP


#define SOGE_REL_COMPILED_SCRIPTING_IMPL_HEADER(Suffix) SOGE_REL_COMPILED_IMPL_HEADER(SOGE_GRAPHICS_IMPL, Suffix)
#define SOGE_ABS_COMPILED_SCRIPTING_IMPL_HEADER(IncludeDir, Suffix)                                                     \
    SOGE_ABS_COMPILED_IMPL_HEADER(SOGE_SCRIPTING_IMPL, IncludeDir, Suffix)

#endif // SOGE_SCRIPTING_SCRIPTINGCOMPILEPREPROC_HPP
